#!/bin/sh
if [ ! -d /data/user/root ]; then
    cat /etc/passwd.d/* > /etc/passwd
    mkdir /data/user/root -p
    chown root /data/user/root
    chmod 700 /data/user/root
    ln -s data/user/root /root

    mkdir -p /dev /sys /proc /run
    ln -s ../run /var/run
else
    exit 0
fi
